version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app-${COMPOSE_PROJECT_NAME} # название контейнера
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - /etc/letsencrypt/live/example.com/fullchain.pem:/etc/letsencrypt/live/example.com/fullchain.pem
      - /etc/letsencrypt/live/example.com/privkey.pem:/etc/letsencrypt/live/example.com/privkey.pem
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver-${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    entrypoint: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'" 
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - app-network
      
  certbot:
    container_name: service_certbot
    image: certbot/certbot
    volumes:
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'" 

  #MySQL Service
  db:
    image: mysql:5.7.22 # тут можно поставить версию mysql
    container_name: db-${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: default # название базы данных
      MYSQL_ROOT_PASSWORD: mvGQ%TS@mA # Пароль Логин root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
## PHPMYAADMIN установка phpmyadmin при входе использовать ip компьютера именно компьютера!
  phpmyadmin:

    image: phpmyadmin/phpmyadmin

    container_name: pma-${COMPOSE_PROJECT_NAME}

    links:

      - db

    environment:

      PMA_HOST: db

      PMA_PORT: 3306

      PMA_ARBITRARY: 1

      UPLOAD_LIMIT: 300M
    restart: always

    ports:

      - 8081:80

volumes:

  dbdata:
#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
